server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    register-with-eureka: true # Whether to register yourself with Eureka. The default value is true
    fetch-registry: true # Whether to retrieve existing information from Eureka server. The default value is true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: gregperlinli:consumer80
    prefer-ip-address: true