server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
eureka:
  client:
    register-with-eureka: true # Whether to register yourself with Eureka. The default value is true
    fetch-registry: true # Whether to retrieve existing information from Eureka server. The default value is true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: gregperlinli:payment8001
    prefer-ip-address: true
#    # The time interval between Eureka client sending heartbeat to server, in seconds
#    lease-renewal-interval-in-seconds: 1
#    # The upper limit of waiting time for Eureka server to receive the last heartbeat, in seconds
#    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gregperlinli.springcloud.entities
  configuration:
    map-underscore-to-camel-case: true