server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# 消费者将要去访问的微服务名称 (注册成功进 Nacos 的微服务生产者)
service-utl:
  nacos-user-service: http://nacos-payment-provider